# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nExuhuWeetVTtmjRCcTwWmmTD3IX5jx
"""

import streamlit as st
import matplotlib.pyplot as plt

# Allocation data from your table
allocation_data = {
    "25-35": {
        "Conservative": {"debt": 70, "debt_label": "A", "equity": 30, "equity_label": "a"},
        "Moderately Conservative": {"debt": 55, "equity": 45},
        "Moderate": {"debt": 40, "equity": 60},
        "Moderately Aggressive": {"debt": 25, "equity": 75},
        "Aggressive": {"debt": 10, "equity": 90}
    },
    "36-45": {
        "Conservative": {"debt": 75, "debt_label": "B", "equity": 25, "equity_label": "b"},
        "Moderately Conservative": {"debt": 60, "equity": 40},
        "Moderate": {"debt": 45, "equity": 55},
        "Moderately Aggressive": {"debt": 30, "equity": 70},
        "Aggressive": {"debt": 15, "equity": 85}
    },
    "46-55": {
        "Conservative": {"debt": 80, "debt_label": "C", "equity": 20, "equity_label": "c"},
        "Moderately Conservative": {"debt": 65, "equity": 35},
        "Moderate": {"debt": 50, "equity": 50},
        "Moderately Aggressive": {"debt": 35, "equity": 65},
        "Aggressive": {"debt": 20, "equity": 80}
    },
    "55-65": {
        "Conservative": {"debt": 85, "debt_label": "D", "equity": 15, "equity_label": "d"},
        "Moderately Conservative": {"debt": 70, "equity": 30},
        "Moderate": {"debt": 55, "equity": 45},
        "Moderately Aggressive": {"debt": 40, "equity": 60},
        "Aggressive": {"debt": 25, "equity": 75}
    },
    "65+": {
        "Conservative": {"debt": 90, "debt_label": "E", "equity": 10, "equity_label": "e"},
        "Moderately Conservative": {"debt": 75, "equity": 25},
        "Moderate": {"debt": 60, "equity": 40},
        "Moderately Aggressive": {"debt": 45, "equity": 55},
        "Aggressive": {"debt": 30, "equity": 70}
    }
}

# Label mappings
fixed_income_labels = {
    "A": "Govt Schemes/AAA Rated Corp FDs",
    "B": "AAA Rated PSU Bonds/Corp FDs",
    "C": "AA rated PSU Bonds/Corp FDs",
    "D": "AA rated Private Bonds/Corp FDs",
    "E": "AA-/A+ Private Bonds"
}
just_trade_labels = {
    "a": "Large Cap Blue Chip/Dividend Stocks",
    "b": "Large Cap Defensive (Utility) Dividends Stocks",
    "c": "Large Cap Stocks",
    "d": "Large & Mid Cap Stocks",
    "e": "Low Cost ETFs, Stock SIPs"
}

# Streamlit UI
st.title("Bajaj Wealth Allocation")

age_group = st.selectbox("Select Age Group", list(allocation_data.keys()))
risk_appetite = st.selectbox("Select Risk Appetite", list(allocation_data[age_group].keys()))

alloc = allocation_data[age_group][risk_appetite]
debt_pct = alloc["debt"]
equity_pct = alloc["equity"]

# For Conservative, show detailed labels
if risk_appetite == "Conservative":
    debt_label = f"Debt ({fixed_income_labels[alloc['debt_label']]})"
    equity_label = f"Equity ({just_trade_labels[alloc['equity_label']]})"
else:
    debt_label = "Debt"
    equity_label = "Equity"

# Pie chart
fig, ax = plt.subplots()
ax.pie([debt_pct, equity_pct], labels=[debt_label, equity_label], autopct='%1.1f%%', startangle=90, colors=["#4F81BD", "#C0504D"])
ax.axis('equal')
st.pyplot(fig)

# Show legend for Conservative allocations
if risk_appetite == "Conservative":
    st.markdown("### Legend")
    st.write(f"**Fixed Income:** {fixed_income_labels[alloc['debt_label']]}")
    st.write(f"**Just Trade:** {just_trade_labels[alloc['equity_label']]}")
